### ISSUE TITLE
ProgressBar issue

### ISSUE THREAD

**Issue by MichelleShih** [fvisin/reseg#4] opened 2016-11-20 15:38 UTC
I use the Ubuntu 14.04. The ProgressBar I have setup can be import , but doesn't work. In the file reseg.py, the code 
```
pbar = ProgressBar(widgets=widgets, maxval=len(x_train), redirect_stdout=True).start()
```
outputs an error
```
Error while formatting 'Cost %(cost)f, DD %(DD)f, UD %(UD)f %(shape)s'
{'DD': None, 'UD': None, 'cost': None, 'shape': None}`
`TypeError: float argument required, not NoneType
```
I guess if i set up the wrong ProgressBar? Can you give me a reliable one?

**Comment by fvisin** [comment] 2016-12-08 09:48
Hi, can you try the `fix_progbar` branch and let me know if it fixes the issue?

**Comment by fvisin** [comment] 2017-06-09 23:13
7 months with no update. Closing.

**Closed by fvisin** 2017-06-09 23:13 UTC

**Comment by brisker** [comment] 2017-06-22 14:05
error when running python evaluate_camvid.py:


```
jcc@jcc:~/PycharmProjects/reseg$ python evaluate_camvid.py
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN not available)
5|True|RGB|None|True|None| |True|(360, 480)|False|False|False|conv3_3|()|()|GlorotUniform , Constant 0.0|rectify|[100, 100]|([1, 1], [1, 1])|(True, True)|GRULayer| |Constant 0.0|0|Gate Gate Gate Constant 0.0|grad|[50, 50]|[(2, 2), (2, 2)]|[(2, 2), (2, 2)]|GlorotUniform, Constant 0.0|rectify|None|None|False|False| |False| |adadelta|None|None,None,None,None|0.0|0.0|500|5000|100|0| | | | | ||
Loading data ...
Processing Camvid SegNet train dataset...
Loading images...
Loading masks...
Processing Camvid SegNet valid dataset...
Loading images...
Loading masks...
Processing Camvid SegNet test dataset...
Loading images...
Loading masks...
load_data Done!
Tot images:701 Train:367 Valid:101 Test:233
# of classes: 12
Building model ...
Input shape: (None, 360, 480, 3)
Vgg: After vgg: (None, 256, 90, 120)
ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 90, 120)
ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 90, 120)
Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 180, 240)
Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 360, 480)
Starting training...
Error while formatting 'Cost %(cost)f, DD %(DD)f, UD %(UD)f %(shape)s'
{'DD': None, 'UD': None, 'cost': None, 'shape': None}
Traceback (most recent call last):
  File "evaluate_camvid.py", line 241, in <module>
    'reload': False
  File "evaluate_camvid.py", line 110, in main
    reload_=params['reload']
  File "/home/jcc/PycharmProjects/reseg/reseg.py", line 834, in train
    redirect_stdout=True).start()
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 606, in start
    self.update(self.min_value, force=True)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 562, in update
    StdRedirectMixin.update(self, value=value)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 150, in update
    DefaultFdMixin.update(self, value=value)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 54, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 493, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 468, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "/home/jcc/PycharmProjects/reseg/utils.py", line 319, in __call__
    self.format)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/widgets.py", line 73, in __call__
    return (format or self.format) % data
TypeError: float argument required, not NoneType
```
Anyone help?
@fvisin 
@marcociccone

**Comment by brisker** [comment] 2017-06-23 07:52
@fvisin 
fixed when using the new branch, thx

**Comment by fvisin** [comment] 2017-06-26 10:29
Hi @brisker, 

you commented on 2 different (closed) issues and sent me 2 emails with the same exact message in 2 days. Please count to 10 before posting or sending emails and try to wait for at least a week before asking again the same question. We try our best to give support on this repo, but we are also busy working on other projects.

Back to your issue, your log looks fine to me and the code seems to be running as intended. Why do you think it's weird? If something looks odd to you, please open a new issue and be more specific about the problem. 

The `fix_progbar` branch fixed the issue with the latest version of progbar, so I am going to merge it in master.
